### ISSUE TITLE
keylogger doesnt send anything

### ISSUE THREAD

**Issue by deleteduser13** [I2rys/ODiscord#10]
I compiled and ran the keylogger on my machine and it doesnt send anything to the server when typing

**Comment by I2rys** [comment]
Hello @deleteduser13,
The keylogger seems to work fine It also sends It's logged messages in the webhook.

**Comment by deleteduser13** [comment]
I Injected the keylogger into my own pc, and when I type it doesnt send anything

**Comment by I2rys** [comment]
This problem has been fixed(We chatted in Discord). The problem was It's because he was using Discord canary webhook which has different fields than the normal Discord webhook.
