### ISSUE TITLE
Short-forms | suggestion

### ISSUE THREAD

**Issue by PndaBoi** [I2rys/ODiscord#12]
Using short forms may not be very useful for the normal user...

People would be curious but would like the full tool name rather than folder names like "ADS", "247AcO" and more...

**Comment by I2rys** [comment]
Hello @PndaBoi,
If you see in the README I added a list of the tools with there real name(Not code name).

**Comment by PndaBoi** [comment]
I am aware but it would be nice if the folders were having their real names...

**Comment by PndaBoi** [comment]
and you hit 200 commits on this repo, that's cool!

**Comment by I2rys** [comment]
> I am aware but it would be nice if the folders were having their real names...

I guess you are right but for now I will not change there codename.

**Comment by I2rys** [comment]
> and you hit 200 commits on this repo, that's cool!

Thank you so much! ♥️
