### ISSUE TITLE
Copy/save emote image without opening Inspector

### ISSUE THREAD

**Issue by BitMap4** [I2rys/ODiscord#6]
Change the unnecessarily long method in [this](https://github.com/I2rys/ODiscord/blob/main/Using%20emoji%20on%20other%20servers%20without%20nitro.txt) as we can just copy/save the image from the context menu (I believe that's what we call it)
![Screenshot 2021-12-23 at 9 58 53 PM](https://user-images.githubusercontent.com/64366765/147267828-2404ae06-2aa9-444c-9109-8045e5a4522d.png)

**Comment by I2rys** [comment]
> Change the unnecessarily long method in [this](https://github.com/I2rys/ODiscord/blob/main/Using%20emoji%20on%20other%20servers%20without%20nitro.txt) as we can just copy/save the image from the context menu (I believe that's what we call it) ![Screenshot 2021-12-23 at 9 58 53 PM](https://user-images.githubusercontent.com/64366765/147267828-2404ae06-2aa9-444c-9109-8045e5a4522d.png)

Hello @BitMap4, the problem with this is that even If you have uploaded the image in your Discord server and If you don't have a nitro you can't use them also you won't be able to use other server's emoji's with this unlike this [method](https://github.com/I2rys/ODiscord/blob/main/Using%20emoji%20on%20other%20servers%20without%20nitro.txt).

**Comment by BitMap4** [comment]
As far as I can tell, your method does the same as this but uses inspector. Please correct me if I'm misunderstanding something.

https://user-images.githubusercontent.com/64366765/147355793-a1261211-c2cc-468f-b230-29ae2f315b41.mov

**Comment by I2rys** [comment]
> As far as I can tell, your method does the same as this but uses inspector. Please correct me if I'm misunderstanding something.
> 
>  Screen.Recording.2021-12-24.at.6.50.24.PM.mov

I really appreciate you making a video and thank you for that, but the problem is If you don't have nitro you can't use other server's emojis as there are disable and this [method](https://github.com/I2rys/ODiscord/blob/main/Using%20emoji%20on%20other%20servers%20without%20nitro.txt) can bypass it and be able to use the disabled emojis without nitro.

**Comment by BitMap4** [comment]
Hmm, I see
